### ISSUE TITLE
A Bug: "ModuleNotFoundError: No module named 'ase'"

### ISSUE THREAD

**Issue by daniel1991zy** [learningmatter-mit/NeuralForceField#13]
Hi, when I run the example of "01_training.py", it appeared the "from ase.build.rotate import rotation_matrix_from_points
ModuleNotFoundError: No module named 'ase'", I checked the source directory, and found there is not a directory named "ase". Can you update this one in the resposity?

**Comment by simonaxelrod** [comment]
Hi Daniel, 

This sounds like a conda environment issue, since the environment should have ase installed (ase is an external package, rather than a module inside of NeuralForceField). Did you create the conda environment as described in the readme? And did you use that environment when running the tutorial? Doing both of those things should fix the issue. 

Simon
