### ISSUE TITLE
Schnet network ethanol data set energy related information

### ISSUE THREAD

**Issue by mukui123** [learningmatter-mit/NeuralForceField#14]
Hello, I tried subtracting the energy of the reference state and using Psi4 software to optimize, but the effect of energy is still a straight line. I would like to know what software is used to calculate the energy of the dataset provided by WuJie and whether it has been optimized? I saw the exact same data set on an sGDML website, but the exact calculation details were not clear.
![image](https://user-images.githubusercontent.com/90401610/192240170-8f41e8ce-716d-4c34-91e2-05801ed8ca41.png)

**Comment by simonaxelrod** [comment]
I'm not sure of the exact method used to generate the data, but the data from any method should be fittable by SchNet. Are you sure that the units are consistent? Are the forces given in units of energy / distance, with the same distance unit used for the coordinates? What happens if you set the force weight to 0 in the loss - does the energy get properly fit then? What if you don't set the force weight to 0, but increase the energy weight in the loss?

**Comment by mukui123** [comment]
> 

Thank you very much for your advice. After I tried to modify the weight, the effect was much better! But the question remains, is the molecular dynamics system here a dynamic equilibrium of multiple ethanol molecules or a single ethanol molecule? Is there a limit to the number of steps? Will it make a big difference?

**Comment by simonaxelrod** [comment]
Nice! The frames come from an MD simulation of a single ethanol molecule. I don't remember the number of steps in the simulation, but I think it was run for a long time and was well-converged.
