### ISSUE TITLE
Small fix suggestion in nn/utils.py

### ISSUE THREAD

**Issue by nickhine** [learningmatter-mit/NeuralForceField#8]
In nn/utils.py I think there is a small omission. You have:
```
   if any(atomsobject.pbc):
        if np.count_nonzero(atomsobject.cell.T-np.diag(np.diagonal(atomsobject.cell.T)))!=0:
            M,N=dis_mat.shape[0],dis_mat.shape[1]
            f=torch.linalg.solve(torch.Tensor(atomsobject.cell.T),(dis_mat.view(-1,3).T)).T
            g=f-torch.floor(f+0.5)
            dis_mat=torch.matmul(g,torch.Tensor(atomsobject.cell))
```

Should this not be:
```
   if any(atomsobject.pbc):
        if np.count_nonzero(atomsobject.cell.T-np.diag(np.diagonal(atomsobject.cell.T)))!=0:
            M,N=dis_mat.shape[0],dis_mat.shape[1]
            f=torch.linalg.solve(torch.Tensor(atomsobject.cell.T).to(device),(dis_mat.view(-1,3).T)).T
            g=f-torch.floor(f+0.5)
            dis_mat=torch.matmul(g,torch.Tensor(atomsobject.cell).to(device))
```
to prevent PyTorch from complaining about the two tensors being on different devices?

As it stands I can't see a way to generate periodic neighbourlists on the GPU without tweaking this bit of code.

**Comment by simonaxelrod** [comment]
Hey @nickhine - thanks for bringing this up and sorry for the late reply. It turns out that we'd identified this a while back in our private repo, but hadn't made the changes publicly. We also made some other changes related to small unit cells. The changes are [here](https://github.com/learningmatter-mit/NeuralForceField/commit/00b1ea2fca61db2bc3758bfa6807d3985da07654). Does that fix things?
